# Generated by Django 6.0.5 on 2026-06-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                upload_to="profile/avatars/", verbose_name="avatar"
            ),
        ),
    ]
