# Generated by Django 6.0.5 on 2026-06-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_comment_default_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="download_count",
        ),
        migrations.RemoveField(
            model_name="project",
            name="last_download",
        ),
        migrations.RemoveField(
            model_name="project",
            name="view_count",
        ),
    ]
